[target.thumbv7em-none-eabihf]
runner = "probe-run - chip stm32f411"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"
rustflags = [
  # According to <https://github.com/esp-rs/esp-hal/tree/main/esp-backtrace>,
  # "force-frame-pointers" is needed for esp-backtrace to work on RISC-V
  # processors such as the one found in the esp32c6. However, it could
  # negatively impact code's performance.
  "-C", "force-frame-pointers",
  # According to <https://defmt.ferrous-systems.com/setup>, "link-arg=-Tdefmt.x"
  # is needed to use defmt. Unfortunately, it causes problems when not using
  # defmt, so it most be commented out when not using defmt.
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlinkall.x",
]

[env]
DEFMT_LOG = "trace"
ESP_LOG = "trace"

[profile.dev]
opt-level="s"

[profile.release]
opt-level="s"

[prov]

